import PDFDocument from 'pdfkit';

const BRAND = {
  blue: '#3B82F6',
  purple: '#8B5CF6',
  cyan: '#06B6D4',
  emerald: '#10B981',
  dark: '#0F172A',
  gray: '#64748B',
};

/**
 * Streams a polished ATS Compatibility Report PDF for a single analysis.
 * @param {import('express').Response} res - the response is piped to directly
 * @param {object} report - the saved report row (camelCase fields)
 */
export function streamAtsReportPdf(res, report) {
  const doc = new PDFDocument({ margin: 50, size: 'A4' });

  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="ResumeIQ-Report-${report.id}.pdf"`);
  doc.pipe(res);

  // Header
  doc.fillColor(BRAND.dark).fontSize(22).font('Helvetica-Bold').text('ResumeIQ — ATS Compatibility Report');
  doc.moveDown(0.3);
  doc.fillColor(BRAND.gray).fontSize(10).font('Helvetica')
    .text(`Generated on ${new Date(report.created_at || Date.now()).toLocaleString()}`);
  doc.moveDown(1);

  // Resume meta
  doc.fillColor(BRAND.dark).fontSize(12).font('Helvetica-Bold').text('Resume Name');
  doc.fillColor(BRAND.gray).font('Helvetica').text(report.resume_name || 'N/A');
  doc.moveDown(0.6);

  // ATS Score — big highlighted number
  doc.fillColor(BRAND.dark).fontSize(12).font('Helvetica-Bold').text('Overall ATS Score');
  doc.fillColor(scoreColor(report.ats_score)).fontSize(36).font('Helvetica-Bold')
    .text(`${report.ats_score}%`);
  doc.moveDown(0.8);

  // Sub-metrics table
  doc.fillColor(BRAND.dark).fontSize(12).font('Helvetica-Bold').text('Match Breakdown');
  doc.moveDown(0.3);
  const metrics = [
    ['Keyword Match', report.keyword_match_pct],
    ['Skill Match', report.skill_match_pct],
    ['Experience Match', report.experience_match_pct],
    ['Education Match', report.education_match_pct],
  ];
  metrics.forEach(([label, value]) => {
    doc.fillColor(BRAND.gray).fontSize(10).font('Helvetica').text(`${label}: `, { continued: true });
    doc.fillColor(BRAND.dark).font('Helvetica-Bold').text(`${value ?? 0}%`);
  });
  doc.moveDown(1);

  // Matching keywords
  section(doc, 'Matching Keywords', report.matching_keywords, BRAND.emerald);
  // Missing keywords
  section(doc, 'Missing Skills', report.missing_keywords, '#EF4444');

  // Suggestions
  doc.fillColor(BRAND.dark).fontSize(12).font('Helvetica-Bold').text('Suggestions');
  doc.moveDown(0.3);
  const suggestions = Array.isArray(report.suggestions) ? report.suggestions : [];
  suggestions.forEach((s, i) => {
    doc.fillColor(BRAND.gray).fontSize(10).font('Helvetica').text(`${i + 1}. ${s}`);
    doc.moveDown(0.2);
  });

  doc.moveDown(1.5);
  doc.fillColor(BRAND.gray).fontSize(8)
    .text('Generated by ResumeIQ — AI Resume Keyword Analyzer', { align: 'center' });

  doc.end();
}

function section(doc, title, items, color) {
  const list = Array.isArray(items) ? items : [];
  doc.fillColor(BRAND.dark).fontSize(12).font('Helvetica-Bold').text(title);
  doc.moveDown(0.2);
  if (list.length === 0) {
    doc.fillColor(BRAND.gray).fontSize(10).font('Helvetica').text('None found.');
  } else {
    doc.fillColor(color).fontSize(10).font('Helvetica').text(list.join('   •   '));
  }
  doc.moveDown(0.8);
}

function scoreColor(score) {
  if (score >= 85) return BRAND.emerald;
  if (score >= 60) return BRAND.blue;
  return '#EF4444';
}
